version: "3.4"
services:
  # Flask API
  backend:
    container_name: backend-nuvemgpt
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api/.env:/api/.env
      - ./api:/api
    command: gunicorn --config /etc/gunicorn.conf.py --timeout 600 --workers=6 --threads=6 --worker-connections=3000 main:api

